### ISSUE TITLE
bug: + not recognized as a valid work

### ISSUE THREAD

**Issue by lukasmwerner** [chilipepperhott/harper#33]
When using the `+` symbol for math equations inside a markdown file I get the following fixes given the following input:
```md
T(n) = T(n-1) + 1
```
Fixes:
```md
1. Replace with: "0"
2. Replace with: "CD"
3. Replace with: "0" 
```

**Comment by lukasmwerner** [comment]
It also appears with `^` so my guess is that this is linked to #31 in origin but should be handled differently.

**Comment by chilipepperhott** [comment]
Fixes have been pushed to master.
