### ISSUE TITLE
"thread 'main' panicked at [...] when slicing

### ISSUE THREAD

**Issue by mawkler** [chilipepperhott/harper#35]
Hi! Thanks this awesome project!

I got this panic in a Lua file when using Harper 0.6.2 as a language server:

```
[ERROR][2024-02-16 20:27:27] .../vim/lsp/rpc.lua:796	"rpc"	"/home/melker/.cargo/bin/harper-ls"	"stderr"	"thread 'main' panicked at /home/melker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/harper-ls-0.6.2/src/tree_sitter_parser.rs:185:32:\nbegin <= end (23 <= 14) when slicing `-----------\n-- Noice --\n-----------\n`\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

Here's what the file looks like (stripped down, but still causing the error):

```lua
-----------
-- Noice --
-----------
```

**Comment by chilipepperhott** [comment]
Hey @mawkler, I see the issue you were running into. Thank you for bringing this to my attention. It looked like a general issue will all comments in all `lua` files. I've fixed it in the latest commit. 

I'm going to close the issue. Feel free if this continues to occur.

**Comment by mawkler** [comment]
@chilipepperhott Great, thank you!
