### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mawkler** [chilipepperhott/harper#37]
Hi! This repo doesn't have a license, which means that it's techincally not FOSS. If your intention is for it to be FOSS, consider [adding a license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) :)

**Comment by chilipepperhott** [comment]
Of course. Consistent with the `crates.io` listing, I've added the appropriate license directly into the repository.

**Comment by mawkler** [comment]
Awesome! 😊
