### ISSUE TITLE
add to mason registry

### ISSUE THREAD

**Issue by chrisgrieser** [chilipepperhott/harper#41]
Seeing that nvim-lspconfig already has a config for harper, it should also be added to [mason](https://github.com/mason-org/mason-registry) as a common method for installing packages in nvim.

**Comment by chilipepperhott** [comment]
I absolutely agree! In fact, a pull request is already awaiting approval:  https://github.com/mason-org/mason-registry/pull/4690

**Comment by chrisgrieser** [comment]
Oh I see. In that case, there is nothing left to do at this repo. Therefore closing this here.
