### ISSUE TITLE
FR: custom dictionary path

### ISSUE THREAD

**Issue by chrisgrieser** [chilipepperhott/harper#42]
Right now, the location of the custom dictionary path is static. It would be useful to name a custom location, e.g. for syncing purposes.

**Comment by chilipepperhott** [comment]
Thanks for the issue!

Right now I'm working on #40. Once I'm done with that, I'll get started on this right away.

**Comment by chilipepperhott** [comment]
Alright. This has been implemented as of the latest release. See [here](https://github.com/chilipepperhott/harper/tree/master/harper-ls#configuration) for details. Thank you for the suggestion!
